### PR TITLE
fix(rls): Update README to include test section

### PR DESCRIPTION
**Pull request by arajkumar**

### CODE REVIEW

**Comment by arajkumar** [comment]
@invincibleJai , I see that the new [fabric8-analytics-lsp-server npm](https://www.npmjs.com/package/fabric8-analytics-lsp-server/v/0.1.54) module has been published(with #103). What is the procedure to get that into vscode extension? From the log I'm assuming that having a commit with "fix(rls)" would do the work.

**Comment by invincibleJai** [comment]
[test]

**Comment by invincibleJai** [comment]
@arajkumar yes, any semantic commit would trigger an npm release. Then can file a PR to update https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/blob/master/package.json#L192

**Comment by arajkumar** [comment]
@invincibleJai, also i see that `/test` is not being honoured. Something wrong the CI configuration?

**Comment by invincibleJai** [comment]
nope i verified on both of ur PRs. It's [test]

**Comment by arajkumar** [comment]
@invincibleJai , I don't see any PR from cenosci for fabric8-analytics-vscode-extension to update the lsp version.

**Comment by invincibleJai** [comment]
That used to work, you can fix it if not working. But again i never went with automated PRs as i need to test and verify so usually filled on my own

**Pull request merged**
